### PR TITLE
draw empty board on games/show

### PR DESCRIPTION
**Pull request by hugolmendez**
Added a functional empty board to the games/show. 
Just plain html and css.  Please review and let me know.

### CODE REVIEW

**Comment by mscoutermarsh** [comment]
woo woo!

Could you post a screenshot of the board in the pull request? Could be helpful :)

Also looks like you have some merge conflicts. You'll need to rebase, fix the conflicts and force push this branch again :)

Rebasing basically means, it will take the latest from master. And then "reapply" each of your commits on top of it.

It probably won't work cleanly the first time & will ask you to resolve conflicts along the way.

This might be helpful http://rypress.com/tutorials/git/rebasing :smiley:

**Comment by hugolmendez** [comment]
board

**Comment by leamerluck** [comment]
Since mike approves and I'm seconding that, I'll merge it. :+1:

**Comment by mscoutermarsh** [comment]
now that, it an AWESOME chess board. :) nice @hugolmendez :smiley:

**Pull request merged**
